trigger:
  - main
pool:
  name: codespaces-d44278-ADO-agent

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: dotnet build $(buildconfiguration)